name: 'ESLint check'
#on: [pull_request]
on:
  push:
    branches-ignore:
      - '**'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gnosis/safe-react-eslint-plus-action@v3.5.0
